### ISSUE TITLE
Budgie Welcome needs a Moka styled icon

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/pocillo#27]
When launching Budgie Welcome our circular logo is displayed.  This jar's with the squarish Moka icons in Plank dock. We need a round thingy in a square 'hole'.

**Comment by HEXcube** [comment]
Budgie Welcome is currently using the icon `distributor-logo-budgie-remix`. We need to submit a Moka styled icon upstream or have one in Pocillo for the time being. And since we've gone official, we'll need to replace the icon as `distributor-logo-ubuntu-budgie` as well

**Comment by Foggalong** [comment]
Yeah, I think an icon with *blah*-ubuntu-budgie with a symlinking to *blah*-budgie-remix will be sufficient

**Comment by fossfreedom** [comment]
@Foggalong any chance we can get a "moka" styled icon soon? - need this to take various screenshots such as the slideshow containing plank, the menu etc.
