### ISSUE TITLE
Feb 8th Feature Freeze

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/pocillo#28]
17.04 Freeze Date is 16th Feb - after which only bugs can be resolved - no new features.

Thus to allow for upload and acceptance by Canonical our new features feature freeze is Feb 8th.

**Comment by Foggalong** [comment]
Noted, updated the [milestone](https://github.com/UbuntuBudgie/pocillo/milestone/2) with the due date. Will try and get all the new additions in by then :)
