### ISSUE TITLE
Missing symbolic icon for Hibernate

### ISSUE THREAD

**Issue by HEXcube** [UbuntuBudgie/pocillo#30]
![Hibernate Button](https://cloud.githubusercontent.com/assets/3755396/24114984/f686ed0e-0dc7-11e7-9a5a-9ffbe92be0aa.png)

Hibernate icon from panel applet is currently not symbolic. Coz of this missing icon, a non-symbolic hibernate icon is used: [system-hibernate](https://github.com/snwh/moka-icon-theme/blob/v5.3.5/Moka/16x16/actions/system-hibernate.png) which links to [system-sleep.png](https://github.com/snwh/moka-icon-theme/blob/v5.3.5/Moka/16x16/actions/system-sleep.png)

![system-sleep](https://github.com/snwh/moka-icon-theme/blob/v5.3.5/Moka/16x16/actions/system-sleep.png?raw=true)

The correctly used symbolic icons:

![system-shutdown-symbolic](https://cdn.rawgit.com/snwh/faba-icon-theme/v4.1.2/Faba/symbolic/actions/system-shutdown-symbolic.svg) [system-shutdown-symbolic](https://github.com/snwh/faba-icon-theme/blob/v4.1.2/Faba/symbolic/actions/system-shutdown-symbolic.svg)
![media-playlist-repeat-symbolic](https://cdn.rawgit.com/snwh/faba-icon-theme/v4.1.2/Faba/symbolic/status/media-playlist-repeat-symbolic.svg) [media-playlist-repeat-symbolic](https://github.com/snwh/faba-icon-theme/blob/v4.1.2/Faba/symbolic/status/media-playlist-repeat-symbolic.svg)
![media-playback-pause-symbolic](https://cdn.rawgit.com/snwh/faba-icon-theme/v4.1.2/Faba/symbolic/actions/media-playback-pause-symbolic.svg) [media-playback-pause-symbolic](https://github.com/snwh/faba-icon-theme/blob/v4.1.2/Faba/symbolic/actions/media-playback-pause-symbolic.svg)

No idea where the lock icon comes from :open_mouth:

**Comment by Foggalong** [comment]
@HEXcube Do gave so many details, except the actual hibernate icon name needed :P

**Comment by HEXcube** [comment]
Had I figured out the icon name this'd have been a pull request instead of an issue :stuck_out_tongue_winking_eye: 

Anyway, I'll place my bets on `system-hibernate-symbolic` as a wild guess. What do u think?

**Comment by Foggalong** [comment]
I really have no idea - icon name conventions never were my strong point

**Comment by HEXcube** [comment]
I tried both `system-hibernate-symbolic` and `system-suspend-hibernate-symbolic` but to no avail. :disappointed: It seems hibernate doesn't have a symbolic icon yet. Or does the applet cache the icons or something? I did update the GTK icon cache though, through `gtk-update-icon-cache` command. I tested on Ubuntu Budgie 17.04 Beta

**Comment by HEXcube** [comment]
I poked around upstream Budgie code and found this bug's already fixed in this pull request: [Link](https://github.com/budgie-desktop/budgie-desktop/pull/785/files) :smiley: On the latest source ([Link](https://github.com/budgie-desktop/budgie-desktop/blob/cf911df8d97d8b25333dff5e2122d96748b10e1a/src/applets/user-indicator/UserIndicatorWindow.vala#L103)) for User Indicator Applet, the icon's changed to `media-playback-pause-symbolic`, same as the suspend icon. However, Budgie 10.2.9 still has the old icon. :disappointed:  See [Link](https://github.com/budgie-desktop/budgie-desktop/blob/v10.2.9/src/panel/applets/user-indicator/UserIndicatorWindow.vala#L103) .

@fossfreedom Can u cherrypick this commit, or is it better to wait for Budgie 10.3? :confused:

**Comment by fossfreedom** [comment]
not a critical issue - so this will be for 10.3

Thanks for digging this out.
