### ISSUE TITLE
merge pocillo and pocillo-mono

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/pocillo#35]
think we can successfully merge these two rather than install under separate icon folders under the pocillo banner

**Comment by Foggalong** [comment]
What is Pocillo mono? Just been looking through the previous commits and got a bit confused about what's going on

**Comment by Foggalong** [comment]
Ah cool cools :)

**Comment by HEXcube** [comment]
Many users find it annoying to see 'out of place' icons on panel. Having a quick fix like this for monochrome icons would help ensure consistency. :relaxed:

**Comment by Foggalong** [comment]
Continued this discussion in #36
