### ISSUE TITLE
Clean Git History

### ISSUE THREAD

**Issue by Foggalong** [UbuntuBudgie/pocillo#36]
I'm gonna do a cleanup of the recent git history: of the 8 there, almost all of them seem to be doing things which get undone or redone almost immediately to the point where it's confusing to see what the changes made actually were.

**Comment by Foggalong** [comment]
Quick summary of what I'm talking about.

* Tilix was [added to Moka](https://github.com/snwh/moka-icon-theme/pull/359) the day after 6551e40dd3cca2bcc0d43eee6fa1281251a7b3e3, f4a8a40d01172514f1633dd1e493bb72fa9dcea0, 0095295bd69a1a55b387a97c6c7697aa4ec372d1, 1e3ff17e750981b9d9ad4c4cfe3c64f6d21bb7d8 were committed to add it here, so these commits are now just unnecessary baggage.
* Faba-Mono was introduced as an inherit & submodule in 37a6907b3502fd56efe01374eb4dee2fb4e5ab28 and then removed next day in 0f7a4688fafef54700b67a8e87ba6d235927f927 and replaced by just including the entire Faba-Mono theme in the repository in 0f7a4688fafef54700b67a8e87ba6d235927f927.
* In 723c4e76179735261574c25727be548d8b789cff this Faba mono folder was then just merged in with the rest of the Pocillo theme.

The last commit is what's confusing me the most: what did copying & merging the folder in do which the inherit didn't? As far as I can see nothing new has been added so the two be functionally the same :confused:

**Comment by Foggalong** [comment]
Just to make sure I wasn't mistaken about the inherit, screenshots to confirm that just having a Faba-Mono dependency and inherit works fine without pulling in the entire theme to this repo:

Without inherit | With inherit
--- | ---
![screenshot_2017-07-20_16-35-07](https://user-images.githubusercontent.com/5920259/28425925-99dc7d1a-6d69-11e7-8335-47004dc12ef9.png) | ![screenshot_2017-07-20_16-35-38](https://user-images.githubusercontent.com/5920259/28425923-99c59c80-6d69-11e7-95bc-ec9a99a2c11a.png)

All that needs adding is a Faba-Mono dependency and this'll be fine

**Comment by fossfreedom** [comment]
ah - in that case - fine - inherit.  As long as at the end of the day all the icons end up under the Pocillo umbrella rather than as a separate /usr/share/icons/xyz folder I'm ok with going for inherit.

I couldn't get it to work before - probably screwed up the git project linking at the time.

**Comment by Foggalong** [comment]
I didn't realise that's why you wanted them merged in like that. Two options for inherits would be:
1. Separate Faba-Mono package as a dependency
2. Faba-Mono submodule with the Pocillo packaging set to pick up the `faba-mono-icons/Faba-Mono` dir

In either case it'll be under the Pocillo umbrella in the menus but a separate icons folder. Is there a reason you want to do it that way? It'll make maintenance a bit trickier and take Pocillo more in the direction of a stand-alone theme rather than just a folder theme to be applied over the top.

**Comment by fossfreedom** [comment]
I certainly don't want another icons folder under /use/share/icons... For end users the iconset list is long enough without yet another iconset they can choose from and wondering what on earth it looks like

**Comment by Foggalong** [comment]
That's fair. It is kinda convoluted to have a 6 long chain of Pocillo inheriting Faba-Mono inheriting Moka inheriting Faba inheriting gnome inheriting hicolor. It's a shame we can't make use of the index.theme `Hidden=True` feature, but to do so we'd have to bundle in additional hidden versions of the themes just for use with Pocillo. Would kinda defeat the point.

As a note, we can't just bring in Faba-Mono into Pocillo like you did in 37a6907b3502fd56efe01374eb4dee2fb4e5ab28 because of licensing:
* [Moka](https://github.com/snwh/moka-icon-theme/blob/master/LICENSE) is CC-BY-SA-4.0
* [Faba](https://github.com/snwh/faba-icon-theme/blob/master/COPYING) is GNU LGPL-3.0+ *or* CC-BY-SA-4.0
* [Pocillo](https://github.com/UbuntuBudgie/pocillo/blob/master/LICENSE) hence has to be CC-BY-SA-4.0 since it uses both
* [Faba-Mono](https://github.com/snwh/faba-mono-icons/blob/master/LICENSE) is GNU GPLv3+

However CC-BY-SA is [only one-way compatible](https://creativecommons.org/2015/10/08/cc-by-sa-4-0-now-one-way-compatible-with-gplv3/) with GPLv3+. TL;DR:

> *[you can adapt] work under CC BY-SA 4.0 and release [it] under GPLv3, but not the reverse*

This means we can't relicense Faba-Mono icons to CC BY-SA 4.0 but we can relicense Pocillo as GPLv3. Then we'd be free to add Faba-Mono icons to Pocillo because they'd both be GPLv3 licensed. If you're wanting to go down the path of making Pocillo stand-alone then that's the first step.

**Comment by fossfreedom** [comment]
very good catch with the licensing.  I didnt know that.  GPLv3+ it is then.

**Comment by Foggalong** [comment]
Heh, no worries! I only know it because I got caught up in figuring it all out when I did something with the Faba/Moka icons in the past. It's kinda weird that a collection of three themes designed to be used together all have different licensing, but I guess that just the way things turned out
