### ISSUE TITLE
Get Tuxedo tux menu icon included

### ISSUE THREAD

**Issue by GrindamN** [UbuntuBudgie/pocillo#42]
We need to include tux menu icon from Tuxedo Computers as part of default package.

**Comment by fossfreedom** [comment]
Tuxedo should really just use a schema override file in  /usr/share/glib-2.0/schemas

name it (for example) tuxedo.gschema.override

contents will be

```
[com.solus-project.budgie-menu]
menu-icon='start-here-symbolic' 
```
change the menu-icon value to whatever the icon name is.

**Comment by fossfreedom** [comment]
no longer interested in this.
